variable "name_prefix" { type = string}
variable "environment" { type = string}
variable "aws_region" { type = string}
variable "aws_region_cd" { type = string}
variable "db_host" { type = string}
variable "db_port" { type = string}
variable "db_secret_arn" { type = string}
variable "allowed_origins" { type = string}
variable "core_datadog_agent_host" { type = string}
variable "core_datadog_version" { type = string}
variable "core_datadog_trace_enabled" { type = string}
variable "core_datadog_runtime_metrics_enabled" { type = string}
variable "core_datadog_logs_injection_enabled" { type = string}
variable "core_datadog_profiling_enabled" { type = string}
variable "core_datadog_trace_sample_rate" { type = string}
variable "image_name" { type = string}
variable "image_tag" { type = string}
variable "enable_datadog_agent" { type = bool}
variable "vpc_id" {type = string}
variable "private_subnet_ids" {type = list(string)}
variable "create_ecr_vpc_link" { type = bool}
variable "application_id" { type = string}
variable "application_name" { type = string}
variable "created_by_email" { type = string}
variable "team" { type = string}
