variable "name_prefix" {}
variable "environment" {}
variable "aws_region" {}
variable "aws_region_cd" {}
variable "db_host" {}
variable "db_port" {}
variable "db_secret_arn" {}
variable "allowed_origins" {}
variable "core_datadog_agent_host" {}
variable "core_datadog_version" {}
variable "core_datadog_trace_enabled" {}
variable "core_datadog_runtime_metrics_enabled" {}
variable "core_datadog_logs_injection_enabled" {}
variable "core_datadog_profiling_enabled" {}
variable "core_datadog_trace_sample_rate" {}
variable "image_name" {}
variable "image_tag" {}
variable "enable_datadog_agent" {}
